[features]
seeds = false
[programs.localnet]
staker = "4RLpP7eio996DqLcSpV2f9mKSXsogSuezJZctmyXzroo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/soliage-dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"